### ISSUE TITLE
getWindDirection

### ISSUE THREAD

**Issue by Alexandr-logrus** [nick7zmail/MajorDoMo-app_openweather#10]
не работает function getWindDirection($degree, $full=false)
работает function getWindDirection($degree, $full='')
пропущено везде Юго-Восток OW_WIND_SW' => 'SW', 
про падёж говорил, ветер Юго-восточный

а вообще показатель сколько человек и как пользуются )))

**Comment by nick7zmail** [comment]
sw давно добавил вроде...

**Comment by Alexandr-logrus** [comment]
так и пост от 12 января, закрывать тебе или мне

**Comment by nick7zmail** [comment]
А, сорян)))мне в почту он как новый пришел почему-то...
