### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by Alexandr-logrus** [nick7zmail/MajorDoMo-app_openweather#12]
https://github.com/nick7zmail/MajorDoMo-app_openweather/blob/616de70f5f9c427682683857432f8d425f3fdebd/modules/app_openweather/app_openweather.class.php#L229
проблема с округлением
про это не уверен в правильности, но вроде б верно
https://github.com/Alexandr-logrus/MajorDoMo-app_openweather/blob/0ff29b37b5e1117693dc8125634eb301ec82b9c8/modules/app_openweather/app_openweather.class.php#L229

https://github.com/Alexandr-logrus/MajorDoMo-app_openweather/blob/0ff29b37b5e1117693dc8125634eb301ec82b9c8/templates/app_openweather/action_usual.html#L51
в обоих html и файлах перевода, обозвал как сумел

**Comment by nick7zmail** [comment]
closed. fixed in new module
