### ISSUE TITLE
ROOT.'cms/cached'

### ISSUE THREAD

**Issue by Alexandr-logrus** [nick7zmail/MajorDoMo-app_openweather#13]
https://github.com/nick7zmail/MajorDoMo-app_openweather/blob/8538de83dc70fc5a87a78d8935e7cf9dcbc2b56f/modules/app_openweather/app_openweather.class.php#L158

**Comment by Alexandr-logrus** [comment]
и ниже, может где еще?

**Comment by nick7zmail** [comment]
Да, есть в планах во всех модулях это поправить. Только всё после 15 числа)) Ща в ремонте весь.

**Comment by Alexandr-logrus** [comment]
в тлг жаловались и далее на неполучение списка городов с овм

**Comment by nick7zmail** [comment]
Done
